# Verbose debugging messages (spams console)
debug: true

# Stops plugin completely, all break events will be ignored.
enabled: true

# Should AFK players be allowed to mine blocks?
allowAFK: false

# Default regen timer it ticks (20 = 1 second)
defaultTimer: 20

# Default Material to use as a placeholder until the block respawns
defaultPlaceholder: BEDROCK

# Comma delimited list of (MATERIAL to Regen),(Resource timer),(Placeholder)
# Must require a valid Minecraft Material, timer and placeholder are optional.
regen:
  - COBBLESTONE,20,AIR