# Verbose debugging messages (spams console)
debug: true

# False when used in live server
devMode: false

#MYSQL Database settings
hostname: 10.0.0.67
port: 3306
dbname: minecraft
table_prefix: faevale_
username: mcuser
password: b@&*94A@FX1n
flags: ?verifyServerCertificate=false&useSSL=false&useUnicode=true&characterEncoding=utf-8