name: FaevaleEngine
main: ca.lightnet.FaevaleEngine.FaevaleEngine
version: 1.4.4
api-version: 1.19
description: Regenerate blocks based on location
depend:
  - Towny
softdepend:
  - Essentials
commands:
  faevale:
    aliases:
      - fv
      - f
    description: Faevale Server Core Plugin
    usage: /<command> help
    permission: faevale.*
      - faevale.admin
    permission-message: "&4You do not have permission to use this command!"