name: MmoBlockRespawn
main: ca.lightnet.mmoblockrespawn.MmoBlockRespawn
version: 1.2.3
api-version: 1.19
description: Regenerate blocks based on location
depend:
  - Towny
softdepend:
  - Essentials
commands:
  regen:
    description: Wilds regeneration plugin
    usage: /<command> [debug|test|help]