name: FaevaleEngine
main: ca.lightnet.FaevaleEngine.FaevaleEngine
version: 1.3.0
api-version: 1.19
description: Regenerate blocks based on location
depend:
  - Towny
softdepend:
  - Essentials
commands:
  faevale:
    description: Faevale Server Core Plugin
    usage: /<command> help